---
- hosts: auroracam
  vars:
    srcdir: /mnt/e/dev/meteorhunting/pi-meteortools/auroracam
    shrdir: /mnt/e/dev/meteorhunting/pi-meteortools/pi
    destdir: ~/source/auroracam
  tasks:
  - name: Ensures {{destdir}} exists
    file: path={{destdir}} state=directory  
  - name: Copy auroracam files
    copy: src={{ item.src }} dest={{ item.dest }} mode={{ item.mode }}
    with_items:
    - {src: '{{srcdir}}/grabImage.py', dest: '{{destdir}}/', mode: '644', backup: no }
    - {src: '{{srcdir}}/makeMP4.sh', dest: '{{destdir}}/', mode: '755', backup: no }
    - {src: '{{srcdir}}/uploadLiveJpg.sh', dest: '{{destdir}}/', mode: '755', backup: no }
    - {src: '{{srcdir}}/checkAuroracam.sh', dest: '{{destdir}}/', mode: '755', backup: no }
    - {src: '{{srcdir}}/archiveData.sh', dest: '{{destdir}}/', mode: '755', backup: no }
    - {src: '{{srcdir}}/config.ini', dest: '{{destdir}}/', mode: '644', backup: no }
  - name: Copy shared files
    copy: src={{ item.src }} dest={{ item.dest }} mode={{ item.mode }}
    with_items:
    - {src: '{{shrdir}}/setExpo.py', dest: '{{destdir}}/', mode: '644', backup: no }
    - {src: '{{shrdir}}/dvrip.py', dest: '{{destdir}}/', mode: '644', backup: no }
    - {src: '{{shrdir}}/annotateImage.py', dest: '{{destdir}}/', mode: '644', backup: no }
    - {src: '{{shrdir}}/sendAnEmail.py', dest: '{{destdir}}/', mode: '644', backup: no }
    - {src: '{{shrdir}}/requirements.txt', dest: '{{destdir}}/', mode: '644', backup: no }
    - {src: '{{shrdir}}/networkCheck.sh', dest: '{{destdir}}/', mode: '754', backup: no }
    - {src: '{{shrdir}}/logTemperature.sh', dest: '{{destdir}}/', mode: '754', backup: no }

  - name: update ipaddress
    lineinfile: 
      path: '{{destdir}}/config.ini'
      regexp: 'IPADDRESS='
      line: 'IPADDRESS=192.168.1.40'
  - name: update data folder
    lineinfile: 
      path: '{{destdir}}/config.ini'
      regexp: 'DATADIR='
      line: 'DATADIR=~/RMS_data/auroracam'
  - name: update logs folder
    lineinfile: 
      path: '{{destdir}}/config.ini'
      regexp: 'LOGDIR='
      line: 'LOGDIR=~/RMS_data/logs'
  - name: update latitude
    lineinfile: 
      path: '{{destdir}}/config.ini'
      regexp: 'LAT='
      line: 'LAT=51.88'
  - name: update longitude
    lineinfile: 
      path: '{{destdir}}/config.ini'
      regexp: 'LON='
      line: 'LON=-1.31'
  - name: update altitude
    lineinfile: 
      path: '{{destdir}}/config.ini'
      regexp: 'ALT='
      line: 'ALT=80'
  - name: update uploadloc
    lineinfile: 
      path: '{{destdir}}/config.ini'
      regexp: 'UPLOADLOC='
      line: 'UPLOADLOC=s3://mjmm-data'
  - name: make sure modules are downloaded
    shell: source ~/venvs/vRMS/bin/activate && pip install -r {{destdir}}/requirements.txt
    # also need sudo apt-get install python3-opencv ffmpeg
    args:
      executable: /bin/bash

  
