# remember to add inline policy to the Lambda to allow s3 bucket to invoke 
# then add s3 trigger on the properties page of the bucket

AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  python3.8
  SAM Template for processRadioData

Globals:
  Function:
    MemorySize: 128
    
Resources:
  processRadioJpgs:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: processRadioJpgs
      Description: uploads latest interesting jpgs
      Handler: processRadioJpgs.lambda_handler
      Runtime: python3.8
      Timeout: 30
      Role: arn:aws:iam::317976261112:role/lambda-s3-full-access-role
      Events:
        createNewJpg:
          Type: S3
          Properties:
            Bucket: !Ref mjmmrawradiodata
            Events: s3:ObjectCreated:*
            Filter:
              S3Key:
                Rules:
                - Name: prefix
                  Value: raw/
                - Name: suffix
                  Value: .jpg
    Metadata:
      BuildMethod: python3.8

  mjmmrawradiodata:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: mjmm-rawradiodata
