# arn:aws:lambda:eu-west-2:317976261112:function:getExtraOrbitFilesV2
# remember to add inline policy to the Lambda to allow s3 bucket to invoke 
# then add s3 trigger on the properties page of the bucket

AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  python3.8
  SAM Template for createCamIndexes

Globals:
  Function:
    MemorySize: 128
    
Resources:
  createCamIndexes:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: createCamIndexes
      Description: Updates camera index files on my website as new files arrive
      Handler: createCamIndexes.lambda_handler
      Runtime: python3.8
      Timeout: 30
      Role: arn:aws:iam::317976261112:role/lambda-s3-full-access-role
      Tags:
        billingtag: "MarksWebsite"
    Metadata:
      BuildMethod: python3.8
  s3InvokeMyFunction:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !GetAtt createCamIndexes.Arn
      Principal: s3.amazonaws.com
      SourceArn: arn:aws:s3:::mjmm-data

