---
- hosts: "{{host | default ('uk0006,uk000f,uk001l,uk002f')}}"
  vars_files: 
    - /mnt/c/Users/{{ lookup('env','USER' )}}/apikeys/mqvariables.enc
  vars:
    srcdir: "/mnt/c/Users/{{ lookup('env','USER' )}}/OneDrive/dev/pi-meteortools/pi"
    destdir: ~/source/tackley-tools
  tasks:
  - name: Ensures {{destdir}}/tmp exists
    file: path={{destdir}}/tmp state=directory  
  - name: Copy meteorhunting files
    copy: src={{ item.src }} dest={{ item.dest }} mode={{ item.mode }}
    with_items:
    - {src: '{{srcdir}}/install.sh', dest: '{{destdir}}/', mode: '755', backup: no }
    - {src: '{{srcdir}}/backupConfig.sh', dest: '{{destdir}}/', mode: '755', backup: no }
    - {src: '{{srcdir}}/recalibrateAndUpload.sh', dest: '{{destdir}}/', mode: '755', backup: no }
    - {src: '{{srcdir}}/resendLive.sh', dest: '{{destdir}}/', mode: '755', backup: no }
    - {src: '{{srcdir}}/trackStarCount.sh', dest: '{{destdir}}/', mode: '755', backup: no }
    - {src: '{{srcdir}}/sendToMQTT.py', dest: '{{destdir}}/', mode: '644', backup: no }
    - {src: '{{srcdir}}/postMatchStats.sh', dest: '{{destdir}}/', mode: '755', backup: no }
    - {src: '{{srcdir}}/sendToYoutube.py', dest: '{{destdir}}/', mode: '644', backup: no }
    - {src: '{{srcdir}}/dailyPostProc.py', dest: '{{destdir}}/', mode: '644', backup: no }
    - {src: '{{srcdir}}/setIPCamExpo.sh', dest: '{{destdir}}/', mode: '755', backup: no }
    - {src: '{{srcdir}}/logToMQTT.sh', dest: '{{destdir}}/', mode: '755', backup: no }
    - {src: '{{srcdir}}/setExpo.py', dest: '{{destdir}}/', mode: '644', backup: no }
    - {src: '{{srcdir}}/config.ini', dest: '{{destdir}}/', mode: '644', backup: no }
    - {src: '{{srcdir}}/requirements.txt', dest: '{{destdir}}/', mode: '644', backup: no }

  - name: update id file
    lineinfile:
      path: '{{destdir}}/config.ini'
      regexp: 'IDFILE='
      line: 'IDFILE=~/.ssh/{{ inventory_hostname }}'
  - name: update AWS host
    lineinfile:
      path: '{{destdir}}/config.ini'
      regexp: 'HOST='
      line: 'HOST=s3://mjmm-data'
  - name: update webserver
    lineinfile:
      path: '{{destdir}}/config.ini'
      regexp: 'WEBSERVER='
      line: 'WEBSERVER=wordpresssite'
  - name: update idserver
    lineinfile:
      path: '{{destdir}}/config.ini'
      regexp: 'IDSERVER='
      line: 'IDSERVER=wordpresssite'
  - name: update MQTT broker
    lineinfile:
      path: '{{destdir}}/config.ini'
      regexp: 'BROKER='
      line: 'BROKER=wxsatpi'
  - name: update MQTT username
    lineinfile:
      path: '{{destdir}}/config.ini'
      regexp: 'USERNAME='
      line: 'USERNAME=rmscams'
  - name: update MQTT password
    lineinfile:
      path: '{{destdir}}/config.ini'
      regexp: 'PASSWORD='
      line: 'PASSWORD={{ rmscampassword }}'
  - name: install cronjobs and python modules
    shell: source ~/vRMS/bin/activate && {{destdir}}/install.sh
    args:
      executable: /bin/bash

  
