---
- hosts: meteorpi, meteorpi2, meteorpi3
  vars:
    srcdir: /mnt/e/dev/meteorhunting/UKMON-shared/Pi_Cameras
    destdir: ~/mjmm
  tasks:
  - name: Copy files
    copy: src={{ item.src }} dest={{ item.dest }} mode={{ item.mode }}
    with_items:
    - {src: '{{srcdir}}/setIPCamExpo.sh', dest: '{{destdir}}', mode: '755', backup: no }
    - {src: '{{srcdir}}/sunwait', dest: '{{destdir}}', mode: '755', backup: no }
    - {src: '{{srcdir}}/postProcess.sh', dest: '{{destdir}}', mode: '755', backup: no }
    - {src: '{{srcdir}}/logTemperature.sh', dest: '{{destdir}}', mode: '755', backup: no }
    - {src: '{{srcdir}}/RMS_Pi4Monitor.sh', dest: '{{destdir}}', mode: '755', backup: no }
    - {src: '{{srcdir}}/clearArchive.sh', dest: '{{destdir}}', mode: '755', backup: no }
    - {src: '{{srcdir}}/SetExpo.py', dest: '{{destdir}}', mode: '644', backup: no }
    - {src: '{{srcdir}}/sendToYoutube.py', dest: '{{destdir}}', mode: '644', backup: no }
    - {src: '{{srcdir}}/config.ini', dest: '{{destdir}}', mode: '644', backup: no }

  - name: update mail recip
    lineinfile: 
      path: ~/mjmm/config.ini
      regexp: 'MAILRECIP='
      line: 'MAILRECIP=markmcintyre99@googlemail.com'
  - name: update id file
    lineinfile:
      path: ~/mjmm/config.ini
      regexp: 'IDFILE='
      #line: 'IDFILE=~/.ssh/markskey.pem'
      line: 'IDFILE=~/.ssh/mjmm-data.key'
  - name: update AWS host
    lineinfile:
      path: ~/mjmm/config.ini
      regexp: 'HOST='
      #line: 'HOST=ec2-3-9-128-14.eu-west-2.compute.amazonaws.com'
      line: 'HOST=s3://mjmm-data'
  - name: update AWS user
    lineinfile:
      path: ~/mjmm/config.ini
      regexp: 'USER='
      line: 'USER=bitnami'
  - name: update target folder
    lineinfile:
      path: ~/mjmm/config.ini
      regexp: 'MP4DIR='
      line: 'MP4DIR=/mnt/mjmm-data/'
    