---
- hosts: wordpresssite
  vars:
    srcdir: /mnt/e/dev/meteorhunting/pi-meteortools/wpserver
    destdir: ~/tools/meteorcampages
  tasks:
  - name: Copy files
    copy: src={{ item.src }} dest={{ item.dest }} mode={{ item.mode }}
    with_items:
    - {src: '{{srcdir}}/makeLatestIndex.py', dest: '{{destdir}}/', mode: '644', backup: no }
    - {src: '{{srcdir}}/latestindex.js', dest: '{{destdir}}/', mode: '644', backup: no }
    - {src: '{{srcdir}}/updateLatestPage.sh', dest: '{{destdir}}/', mode: '755', backup: no }
    - {src: '{{srcdir}}/createCamIndex.sh', dest: '{{destdir}}/', mode: '755', backup: no }
    - {src: '{{srcdir}}/createRmoblist.sh', dest: '{{destdir}}/', mode: '755', backup: no }
    - {src: '{{srcdir}}/getLatestRadioJpgs.sh', dest: '{{destdir}}/', mode: '755', backup: no }
    - {src: '{{srcdir}}/config.ini', dest: '{{destdir}}/', mode: '644', backup: no }
    - {src: '{{srcdir}}/radiostation.ini', dest: '{{destdir}}/', mode: '644', backup: no }
  - name: update DATADIR
    lineinfile:
      path: '{{destdir}}/config.ini'
      regexp: 'export DATADIR='
      line: 'export DATADIR=~/data/mjmm-data'
  - name: update TMPDIR
    lineinfile:
      path: '{{destdir}}/config.ini'
      regexp: 'export TMPDIR='
      line: 'export TMPDIR={{destdir}}/tmp'
  - name: Ensures tmpdir exists
    file: path={{destdir}}/tmp state=directory  
  - name: update LATI
    lineinfile:
      path: '{{destdir}}/config.ini'
      regexp: 'export LATI='
      line: 'export LATI=51.88'
  - name: update LONGI
    lineinfile:
      path: '{{destdir}}/config.ini'
      regexp: 'export LONGI='
      line: 'export LONGI=-1.31'
  - name: update ALTI
    lineinfile:
      path: '{{destdir}}/config.ini'
      regexp: 'export ALTI='
      line: 'export ALTI=80'

