---
- hosts: uk001l
  vars_files: 
    - /mnt/c/Users/{{ lookup('env','USER' )}}/apikeys/mqvariables.enc
  vars:
    srcdir: "/mnt/c/Users/{{ lookup('env','USER' )}}/OneDrive/dev/meteorhunting/pi-meteortools/pi"
    destdir: ~/source/tackley-tools
  tasks:
  - name: Ensures {{destdir}}/tmp exists
    file: path={{destdir}}/tmp state=directory  
  - name: Copy meteorhunting files
    copy: src={{ item.src }} dest={{ item.dest }} mode={{ item.mode }}
    with_items:
    - {src: '{{srcdir}}/install.sh', dest: '{{destdir}}/', mode: '755', backup: no }
    - {src: '{{srcdir}}/backupConfig.sh', dest: '{{destdir}}/', mode: '755', backup: no }
    - {src: '{{srcdir}}/recalibrateAndUpload.sh', dest: '{{destdir}}/', mode: '755', backup: no }
    - {src: '{{srcdir}}/reprocessCam.sh', dest: '{{destdir}}/', mode: '755', backup: no }
    - {src: '{{srcdir}}/resendLive.sh', dest: '{{destdir}}/', mode: '755', backup: no }
    - {src: '{{srcdir}}/sendToYoutube.py', dest: '{{destdir}}/', mode: '644', backup: no }
    - {src: '{{srcdir}}/dailyPostProc.py', dest: '{{destdir}}/', mode: '644', backup: no }
    - {src: '{{srcdir}}/setIPCamExpo.sh', dest: '{{destdir}}/', mode: '755', backup: no }
    - {src: '{{srcdir}}/setExpo.py', dest: '{{destdir}}/', mode: '644', backup: no }
    - {src: '{{srcdir}}/tackleyUtils.py', dest: '{{destdir}}/', mode: '644', backup: no }
    - {src: '{{srcdir}}/requirements.txt', dest: '{{destdir}}/', mode: '644', backup: no }
    - {src: '{{srcdir}}/config.ini.sample', dest: '{{destdir}}/config.ini', mode: '644', backup: no }

  - name: update id server
    lineinfile:
      path: '{{destdir}}/config.ini'
      regexp: 'IDSERVER='
      line: 'IDSERVER=wordpresssite'
  - name: update id file
    lineinfile:
      path: '{{destdir}}/config.ini'
      regexp: 'IDFILE='
      line: 'IDFILE=~/.ssh/tackley'
  - name: update AWS host
    lineinfile:
      path: '{{destdir}}/config.ini'
      regexp: 'HOST='
      line: 'HOST=s3://mjmm-data'
  - name: update webserver
    lineinfile:
      path: '{{destdir}}/config.ini'
      regexp: 'WEBSERVER='
      line: 'WEBSERVER=wordpresssite'
  - name: update backup target
    lineinfile:
      path: '{{destdir}}/config.ini'
      regexp: 'TARGET='
      line: 'TARGET=thelinux'
  - name: update backup location
    lineinfile:
      path: '{{destdir}}/config.ini'
      regexp: 'REMOTEPATH='
      line: 'REMOTEPATH=/data3/astrodata/meteorcam'
  - name: update station1
    lineinfile:
      path: '{{destdir}}/config.ini'
      regexp: 'ID1='
      line: 'ID1=UK001L'
  #- name: install cronjobs and python modules
  #  shell: source ~/vRMS/bin/activate && {{destdir}}/install.sh
  #  args:
  #    executable: /bin/bash
