---
- hosts: "{{host | default ('uk0006, uk000f, uk001l, uk002f, testpi3, testpi4')}}"
  vars:
    srcdir: /mnt/e/dev/meteorhunting/pi-meteortools/pi
    destdir: ~/mjmm
  tasks:
  - name: Ensures {{destdir}}/tmp exists
    file: path={{destdir}}/tmp state=directory  
  - name: Copy meteorhunting files
    copy: src={{ item.src }} dest={{ item.dest }} mode={{ item.mode }}
    with_items:
    - {src: '{{srcdir}}/clearArchive.sh', dest: '{{destdir}}/', mode: '755', backup: no }
    - {src: '{{srcdir}}/trackFFs.sh', dest: '{{destdir}}/', mode: '755', backup: no }
    - {src: '{{srcdir}}/backupConfig.sh', dest: '{{destdir}}/', mode: '755', backup: no }
    - {src: '{{srcdir}}/sendToYoutube.py', dest: '{{destdir}}/', mode: '644', backup: no }
    - {src: '{{srcdir}}/dailyPostProc.py', dest: '{{destdir}}/', mode: '644', backup: no }
    - {src: '{{srcdir}}/sendToMQTT.py', dest: '{{destdir}}/', mode: '644', backup: no }
    - {src: '{{srcdir}}/sendAnEmail.py', dest: '{{destdir}}/', mode: '644', backup: no }
    - {src: '{{srcdir}}/logGrabInterval.sh', dest: '{{destdir}}/', mode: '755', backup: no }
    - {src: '{{srcdir}}/annotateImage.py', dest: '{{destdir}}/', mode: '644', backup: no }
    - {src: '{{srcdir}}/requirements.txt', dest: '{{destdir}}/', mode: '644', backup: no }
    - {src: '{{srcdir}}/setIPCamExpo.sh', dest: '{{destdir}}/', mode: '755', backup: no }
    - {src: '{{srcdir}}/networkCheck.sh', dest: '{{destdir}}/', mode: '755', backup: no }
    - {src: '{{srcdir}}/logTemperature.sh', dest: '{{destdir}}/', mode: '755', backup: no }
    - {src: '{{srcdir}}/SetExpo.py', dest: '{{destdir}}/', mode: '644', backup: no }
    - {src: '{{srcdir}}/config.ini', dest: '{{destdir}}/', mode: '644', backup: no }

  #- name: update mail recip
  #  lineinfile: 
  #    path: '{{destdir}}/config.ini'
  #    regexp: 'MAILRECIP='
  #    line: 'MAILRECIP=markmcintyre99@googlemail.com'
  - name: update id file
    lineinfile:
      path: '{{destdir}}/config.ini'
      regexp: 'IDFILE='
      line: 'IDFILE=~/.ssh/mjmm-data.key'
  - name: update AWS host
    lineinfile:
      path: '{{destdir}}/config.ini'
      regexp: 'HOST='
      line: 'HOST=s3://mjmm-data'
  - name: update AWS user
    lineinfile:
      path: '{{destdir}}/config.ini'
      regexp: 'USER='
      line: 'USER=bitnami'
  - name: update webserver
    lineinfile:
      path: '{{destdir}}/config.ini'
      regexp: 'WEBSERVER='
      line: 'WEBSERVER=3.9.128.14'
  - name: update webid
    lineinfile:
      path: '{{destdir}}/config.ini'
      regexp: 'WEBID='
      line: 'WEBID=/home/pi/.ssh/markskey.pem'
  - name: update target folder
    lineinfile:
      path: '{{destdir}}/config.ini'
      regexp: 'MP4DIR='
      line: 'MP4DIR=/mnt/mjmm-data/'
  - name: update MQTT broker
    lineinfile:
      path: '{{destdir}}/config.ini'
      regexp: 'BROKER='
      line: 'BROKER=wxsatpi'
  - name: make sure modules are downloaded
    shell: source ~/vRMS/bin/activate && pip install -r {{destdir}}/requirements.txt
    args:
      executable: /bin/bash

  