# sunwait
#
# MSVC version of the makefile
# 08/12/2014  IFC  0.6  No changes since 0.5
# 02/05/2015  IFC  0.7  No changes since 0.5, still
#

CFLAGS=-c -Wall 
SOURCES=sunwait.cpp sunriset.cpp print.cpp sunwait.h sunriset.h print.h
C=cl
LDFLAGS=
OBJECTS=sunwait.obj sunriset.obj print.obj
EXECUTABLE=sunwait.exe

all: $(SOURCES) $(EXECUTABLE)
	
$(EXECUTABLE): $(OBJECTS)
	$(C) $(OBJECTS) -o $@ 

.cpp.o:
	$(C) $(CFLAGS) $< -o $@

clean:
	del $(OBJECTS) $(EXECUTABLE)
