[
  {
    name: 'utility 1',
    id: 'utility1id',
    key: 'utility1key'
  },
  {
    name: 'chest freezer',
    id: 'chestfreezerid',
    key: 'chestfreezerkey'
  },
  { 
     name: 'fan', 
     id: 'fanid', 
     key: 'fankey' 
  },
  {
    name: 'utility 2',
    id: 'utility2id',
    key: "utility2key"
  },
  {
    name: 'Smart Socket',
    id: 'smartsocketid',
    key: 'smartsocketkey'
  }
]

