# remember to add inline policy to the Lambda to allow s3 bucket to invoke 
# then add s3 trigger on the properties page of the bucket

AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  python3.8
  SAM Template for latestWXImages

Globals:
  Function:
    MemorySize: 512
    
Resources:
  latestWXImages:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: latestWXImages
      Description: creates latest versions of NOAA and M2 images
      Handler: latestWxImages.lambda_handler
      Runtime: python3.8
      Timeout: 120
      Role: arn:aws:iam::317976261112:role/lambda-s3-full-access-role
      Tags:
        billingtag: "MarksWebsite"
      Environment:
        Variables:
          MPLCONFIGDIR: /tmp/mpl
      Events:
        createNewWxFile:
          Type: S3
          Properties:
            Bucket: !Ref mjmmrawsatdata
            Events: s3:ObjectCreated:*
            Filter:
              S3Key:
                Rules:
                - Name: prefix
                  Value: satimgs
                - Name: suffix
                  Value: .jpg
    Metadata:
      BuildMethod: python3.8
  mjmmrawsatdata:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: mjmm-rawsatdata
      Tags:
      - Key: "billingtag"
        Value: "MarksWebsite"
