# config file for MeteorRadio
export SNR=30
export GAIN=50
export SRCDIR=$HOME/source/MeteorRadio/src
export LOGDIR=$HOME/radar_data/Logs
export VERBOSE=  # set this to 1 to get verbose logging or leave blank to disable