# config file for MeteorRadio
export SNR=30
export GAIN=50
export SRCDIR=$HOME/source/MeteorRadio/src
export LOGDIR=$HOME/radar_data/Logs
export VERBOSE=0  # set this to 1 to get verbose logging or 0 to disable
export EXTRAPARAMS=" --detectionband -220 20 --noiseband -600 400"
