# config file
[postprocess]
UPLOAD=1
IDSERVER=
IDFILE=
HOST=
WEBSERVER=
RMSDIR=~/source/RMS
[mqtt]
BROKER=
USERNAME=
PASSWORD=
[backup]
TARGET=thelinux
REMOTEPATH=/data3/astrodata/meteorcam
[stations]
ID1=UK0006
ID2=UK000F
ID3=UK002F
