# remember to add inline policy to the Lambda to allow s3 bucket to invoke 
# then add s3 trigger on the properties page of the bucket

AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  python3.8
  SAM Template for processRadioData

Globals:
  Function:
    MemorySize: 512
    
Resources:
  processRadioData:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: processRadioData
      Description: creates colorgram and heatmaps from RMOB dat file
      Handler: processRadioData.lambda_handler
      Runtime: python3.11
      Timeout: 120
      Role: arn:aws:iam::317976261112:role/lambda-s3-full-access-role
      Tags:
        billingtag: "MarksWebsite"
      Environment:
        Variables:
          MPLCONFIGDIR: /tmp/mpl
      Events:
        createNewDatFile:
          Type: S3
          Properties:
            Bucket: !Ref mjmmrawradiodata
            Events: s3:ObjectCreated:*
            Filter:
              S3Key:
                Rules:
                - Name: prefix
                  Value: raw/event_log
                - Name: suffix
                  Value: .csv
    Metadata:
      BuildMethod: python3.11
      
  processRadioJpgs:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: processRadioJpgs
      CodeUri: ./processRadioJpgs
      Description: uploads latest interesting jpgs
      Handler: processRadioJpgs.lambda_handler
      Runtime: python3.11
      Timeout: 30
      Role: arn:aws:iam::317976261112:role/lambda-s3-full-access-role
      Tags:
        billingtag: "MarksWebsite"
      Events:
        createNewJpg:
          Type: S3
          Properties:
            Bucket: !Ref mjmmrawradiodata
            Events: s3:ObjectCreated:*
            Filter:
              S3Key:
                Rules:
                - Name: prefix
                  Value: raw/
                - Name: suffix
                  Value: .jpg
    Metadata:
      BuildMethod: python3.11

  mjmmrawradiodata:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: mjmm-rawradiodata
      Tags:
      - Key: "billingtag"
        Value: "MarksWebsite"
