name: testing 
on:
    push:
        branches: master
jobs:
    apitests:
        runs-on: pmt-runner
        steps:
        - uses: actions/checkout@v3
        - run: chmod +x ./tests/*.sh
        - run: ./tests/api_tests.sh
