---
# YAML file to install the build scripts on my pi
- hosts: meteorpi
  vars:
    srcdir: /mnt/e/dev/meteorhunting/UKMON-shared/Pi_Cameras/installer
    destdir: ~/installer
  tasks:
  - name: create livedir
    file: path={{destdir}}/live state=directory recurse=yes  
  - name: create archdir
    file: path={{destdir}}/arch state=directory recurse=yes  
  - name: Copy files
    copy: src={{ item.src }} dest={{ item.dest }} mode={{ item.mode }}
    with_items:
    - {src: '{{srcdir}}/builder.sh', dest: '{{destdir}}', mode: '755', backup: no }
    - {src: '{{srcdir}}/inst.template', dest: '{{destdir}}', mode: '644', backup: no }
    - {src: '{{srcdir}}/live/liveMonitor.sh', dest: '{{destdir}}/live', mode: '755', backup: no }
    - {src: '{{srcdir}}/live/liveUploader.sh', dest: '{{destdir}}/live', mode: '755', backup: no }
    - {src: '{{srcdir}}/live/updateKeys.sh', dest: '{{destdir}}/live', mode: '755', backup: no }
    - {src: '{{srcdir}}/live/template.xml', dest: '{{destdir}}/live', mode: '644', backup: no }
    - {src: '{{srcdir}}/live/.ukmondec', dest: '{{destdir}}/live', mode: '755', backup: no }
    - {src: '{{srcdir}}/arch/archToUkMon.sh', dest: '{{destdir}}/arch', mode: '755', backup: no }
    - {src: '{{srcdir}}/live/updateKeys.sh', dest: '{{destdir}}/arch', mode: '755', backup: no }
    - {src: '{{srcdir}}/arch/.ukmondec', dest: '{{destdir}}/arch', mode: '755', backup: no }

  - name: build the live installer after deployment
    shell: 
      cmd: '{{destdir}}/builder.sh live'

  - name: build the arch installer after deployment
    shell: 
      cmd: '{{destdir}}/builder.sh arch'

  - name: fetch built files
    fetch: src={{ item.src }} dest={{ item.dest }} flat=yes
    with_items:
    - {src: '{{destdir}}/installUkMonlive.sh', dest: '../'}
    - {src: '{{destdir}}/installUkMonarch.sh', dest: '../'}

    